apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-kubernetes-read
rules:
- apiGroups:
  - ""
  - apps
  - batch
  resources:
  - pods
  - services
  - deployments
  - replicasets
  - namespaces
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-kubernetes-read-binding
subjects:
- kind: ServiceAccount
  name: backstage-kubernetes
  namespace: backstage

roleRef:
  kind: ClusterRole
  name: backstage-kubernetes-read
  apiGroup: rbac.authorization.k8s.io
