apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: PINJALA780
spec:
  memberOf:
    - guests

---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []

---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: group:default/guests

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-service
  description: Payment Microservice
  annotations:
    backstage.io/kubernetes-id: payment-service
spec:
  type: service
  lifecycle: development
  owner: group:default/guests
  system: examples

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: payment-api
spec:
  type: openapi
  lifecycle: development
  owner: group:default/guests
