replicaCount: 1

image:
  repository: docker.io/${{ values.owner }}/${{ values.name }}
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: false
  className: nginx
  host: ${{ values.name }}.local

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
